### ISSUE TITLE
BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

### ISSUE THREAD

**Issue by AtharvaJaiswal005** [mehranshakarami/AI_Spectrum#12]
BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

**Comment by lemoncookieandapplejuice** [comment]
Hi, I met the same problem, did you solve it? 😭

**Comment by AtharvaJaiswal005** [comment]
I solved the issue where the twikit library was blocking the login flow when using the script. The solution involves manually creating a cookies.json file.

**Steps to create the cookies.json file:**
1-Install a "Cookies Editor" extension on your browser.
2-Log in to [x.com](https://x.com/) (formerly Twitter).
3-Using the extension, extract the necessary cookie values after logging in.
4-Save these values in a cookies.json file. If some keys are missing (like att in my case), you can ignore them.
Below is the JSON format you need to follow when creating the cookies.json file:
{
    "guest_id_marketing": "your_value",
    "guest_id_ads": "your_value",
    "personalization_id": "your_value",
    "guest_id": "your_value",
    "att": "your_value", // Ignore if missing
    "kdt": "your_value",
    "twid": "your_value",
    "ct0": "your_value",
    "auth_token": "your_value"
}
Once you've saved the file with these values, you'll be able to scrape tweets successfully.
